//! Renders a complete `flake.nix` from a [`DevShellDefinition`].
//!
//! This module orchestrates the section renderers (inputs, `let`
//! bindings, `buildInputs`, shell hook) and stitches them into the
//! final flake template. The per-section logic lives in the submodules.

mod build_inputs;
mod path;
mod pinned;
mod shell_hook;
mod test_runner;

use crate::DevShellDefinition;

use build_inputs::render_build_inputs;
use shell_hook::compose_shell_hook;

/// Default stable nixpkgs revision, used unless overridden by settings.
const DEFAULT_STABLE_URL: &str = "github:NixOS/nixpkgs/nixos-25.11";

fn render_inputs_section(stable_url: &str, resolved: &[&crate::PinnedPackageEntry]) -> String {
    let mut lines = vec![
        format!("    nixpkgs.url = \"{}\";", stable_url),
        "    nixpkgs-unstable.url = \"github:NixOS/nixpkgs/nixos-unstable\";".to_string(),
        "    flake-utils.url = \"github:numtide/flake-utils\";".to_string(),
    ];
    let pinned_inputs = pinned::render_inputs(resolved);
    if !pinned_inputs.is_empty() {
        lines.push(pinned_inputs);
    }
    lines.join("\n")
}

fn render_let_section(allow_unfree: bool, resolved: &[&crate::PinnedPackageEntry]) -> String {
    let mut bindings = vec![
        format!(
            "        stablePackages = import nixpkgs {{\n          inherit system;\n          config.allowUnfree = {};\n        }};",
            allow_unfree
        ),
        format!(
            "        unstablePackages = import nixpkgs-unstable {{\n          inherit system;\n          config.allowUnfree = {};\n        }};",
            allow_unfree
        ),
    ];
    let pinned_bindings = pinned::render_let_bindings(resolved, allow_unfree);
    if !pinned_bindings.is_empty() {
        bindings.push(pinned_bindings);
    }
    bindings.join("\n")
}

/// Renders the `flake.nix` content for `config`.
///
/// `override_stable_package` replaces the default stable nixpkgs input
/// when provided (e.g. to pin a different channel or a fork).
pub fn render_flake(config: &DevShellDefinition, override_stable_package: Option<&str>) -> String {
    let allow_unfree = config.dev_shell.allow_unfree;
    let stable_url = override_stable_package.unwrap_or(DEFAULT_STABLE_URL);
    let resolved_pinned = pinned::collect_resolved(config);

    let inputs_section = render_inputs_section(stable_url, &resolved_pinned);
    let pinned_output_params = pinned::render_output_params(&resolved_pinned);
    let let_section = render_let_section(allow_unfree, &resolved_pinned);
    let build_inputs = render_build_inputs(config, &resolved_pinned);
    let shell_hook = compose_shell_hook(config);

    format!(
        r#"# Generated by LazyNix - DO NOT EDIT MANUALLY
# This file is automatically generated from lazynix.yaml
# To make changes, edit lazynix.yaml and run: lnix develop

{{
  description = "DevShell generated by LazyNix";

  inputs = {{
{}
  }};

  outputs = {{ self, nixpkgs, nixpkgs-unstable, flake-utils{} }}:
    flake-utils.lib.eachDefaultSystem (system:
      let
{}
      in
      {{
        devShells.default = stablePackages.mkShell {{
          buildInputs = [
{}
          ];

          shellHook = ''
{}
          '';
        }};
      }}
    );
}}
"#,
        inputs_section, pinned_output_params, let_section, build_inputs, shell_hook
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    const BASIC: &str = "devShell:\n  package:\n    stable:\n      - name: bash\n";

    fn render_from_yaml(yaml: &str, override_url: Option<&str>) -> String {
        let config: DevShellDefinition = serde_yaml::from_str(yaml).unwrap();
        render_flake(&config, override_url)
    }

    #[test]
    fn uses_override_stable_url_when_provided() {
        // Arrange
        let custom_url = "github:NixOS/nixpkgs/nixos-25.06";

        // Act
        let flake = render_from_yaml(BASIC, Some(custom_url));

        // Assert
        assert!(flake.contains(&format!("nixpkgs.url = \"{}\";", custom_url)));
        assert!(!flake.contains("nixpkgs.url = \"github:NixOS/nixpkgs/nixos-25.11\";"));
    }

    #[test]
    fn falls_back_to_default_stable_url() {
        // Arrange / Act
        let flake = render_from_yaml(BASIC, None);

        // Assert
        assert!(flake.contains("nixpkgs.url = \"github:NixOS/nixpkgs/nixos-25.11\";"));
    }

    #[test]
    fn propagates_allow_unfree_flag() {
        // Arrange
        let yaml = "devShell:\n  allowUnfree: false\n  package:\n    stable:\n      - name: bash\n";

        // Act
        let flake = render_from_yaml(yaml, None);

        // Assert
        assert!(flake.contains("config.allowUnfree = false"));
    }

    #[test]
    fn renders_pinned_package_end_to_end() {
        // Arrange
        let yaml = r#"
devShell:
  package:
    stable:
      - name: bash
    pinned:
      - name: go
        version: "1.21.13"
        resolvedCommit: "e607cb5"
        resolvedAttr: "go_1_21"
"#;

        // Act
        let flake = render_from_yaml(yaml, None);

        // Assert: input, let binding, and buildInputs entry all present
        assert!(flake.contains("nixpkgs--go--1-21-13.url = \"github:NixOS/nixpkgs/e607cb5\";"));
        assert!(flake.contains("pinnedPkgs-go-1-21-13 = import nixpkgs--go--1-21-13"));
        assert!(flake.contains("pinnedPkgs-go-1-21-13.go_1_21"));
    }

    #[test]
    fn skips_unresolved_pinned_package() {
        // Arrange
        let yaml = r#"
devShell:
  package:
    stable:
      - name: bash
    pinned:
      - name: go
        version: "1.21.13"
"#;

        // Act
        let flake = render_from_yaml(yaml, None);

        // Assert
        assert!(!flake.contains("nixpkgs--go--1-21-13"));
        assert!(!flake.contains("pinnedPkgs-go"));
    }
}
