# Generated by LazyNix - DO NOT EDIT MANUALLY
# This file is automatically generated from lazynix.yaml
# To make changes, edit lazynix.yaml and run: lnix develop

{
  description = "DevShell generated by LazyNix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs--go--1-21-13.url = "github:NixOS/nixpkgs/5ed6275";
  };

  outputs = { self, nixpkgs, nixpkgs-unstable, flake-utils, nixpkgs--go--1-21-13 }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        stablePackages = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
        unstablePackages = import nixpkgs-unstable {
          inherit system;
          config.allowUnfree = true;
        };
        pinnedPkgs-go-1-21-13 = import nixpkgs--go--1-21-13 {
          inherit system;
          config.allowUnfree = true;
        };
      in
      {
        devShells.default = stablePackages.mkShell {
          buildInputs = [
            # Stable packages
            stablePackages.python312
            stablePackages.uv
            # Pinned packages
            pinnedPkgs-go-1-21-13.go_1_21
          ];

          shellHook = ''
            echo Python $(python --version) ready!
            echo Go $(go version) ready!
          '';
        };
      }
    );
}
